spring.application.name=soundock

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=warn

app.frontend.success-url=${FRONTEND_URL}/verify-success
app.frontend.fail-url=${FRONTEND_URL}/verify-fail

# smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# signup Email baseUrl
app.base.url=${BACKEND_URL}

server.forward-headers-strategy=native

jwt.refresh-token-validity=${JWT_REFRESH_TOKEN_VALIDITY}
spring.jwt.secret=${JWT_SECRET_KEY}

# swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email,https://www.googleapis.com/auth/youtube.readonly
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# OAuth2AuthenticationSuccessHandler
app.cookie.secure=${COOKIE_SECURE:false}
app.frontend.url=${FRONTEND_URL}


# toss payments
toss.client.key=${TOSS_CLIENT_KEY}
toss.secret.key=${TOSS_SECRET_KEY}

server.port=8080

app.alb.url=${ALB_URL:http://localhost:8080}

spring.devtools.livereload.enabled=true
spring.freemarker.cache=false
spring.thymeleaf.cache=false

logging.level.root=info
logging.level.dopamine.soundock=info


# OAuth2 SecurityConfig
oauth.request.dev=${OAUTH_DEV_MODE:false}

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# email search
search.email.login=${SEARCH_EMAIL_LOGIN}
search.email.signup=${SEARCH_EMAIL_SIGNUP}

# Passwordless Serving API URL
pwl.serving.url=${PWL_SERVING_URL}
pwl.base.url=${PWL_BASE_URL}
pwl.server.key=${PWL_SERVER_KEY}


# AWS S3 Configuration

# max file size for upload
spring.servlet.multipart.max-file-size=10MB

# max entire size for request
spring.servlet.multipart.max-request-size=10MB

spring.cloud.aws.s3.bucket=${AWS_BUCKET}
spring.cloud.aws.credentials.access-key=${AWS_BUCKET_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_BUCKET_SECRET_KEY}
spring.cloud.aws.region.static=${AWS_REGION_STATIC}

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=2

# time zone
spring.jackson.time-zone=Asia/Seoul

# cookie domain
app.cookie.domain=${SERVER_DOMAIN}